export const ROLES = {
  ADMIN: 'ADMIN',
  GERENTE: 'GERENTE',
  SUPERVISOR: 'SUPERVISOR',
  MECANICO: 'MECANICO',
  RECEPCIONISTA: 'RECEPCIONISTA',
  ALMACEN: 'ALMACEN',
  CONTABILIDAD: 'CONTABILIDAD',
} as const;

export type Rol = (typeof ROLES)[keyof typeof ROLES];

export const MODULOS = {
  DASHBOARD: 'DASHBOARD',
  VEHICULOS_CLIENTES: 'VEHICULOS_CLIENTES',
  ORDENES_TRABAJO: 'ORDENES_TRABAJO',
  SERVICIOS_CATALOGO: 'SERVICIOS_CATALOGO',
  AGENDA_CITAS: 'AGENDA_CITAS',
  INVENTARIO: 'INVENTARIO',
  FACTURACION: 'FACTURACION',
  REPORTES: 'REPORTES',
  USUARIOS: 'USUARIOS',
  CONFIGURACION: 'CONFIGURACION',
} as const;

export type Modulo = (typeof MODULOS)[keyof typeof MODULOS];

export type NivelPermiso = 'COMPLETO' | 'LECTURA' | 'SIN_ACCESO';

export const PERMISOS_POR_ROL: Record<Rol, Record<Modulo, NivelPermiso>> = {
  ADMIN: {
    DASHBOARD: 'COMPLETO', VEHICULOS_CLIENTES: 'COMPLETO', ORDENES_TRABAJO: 'COMPLETO',
    SERVICIOS_CATALOGO: 'COMPLETO', AGENDA_CITAS: 'COMPLETO', INVENTARIO: 'COMPLETO',
    FACTURACION: 'COMPLETO', REPORTES: 'COMPLETO', USUARIOS: 'COMPLETO', CONFIGURACION: 'COMPLETO',
  },
  GERENTE: {
    DASHBOARD: 'COMPLETO', VEHICULOS_CLIENTES: 'COMPLETO', ORDENES_TRABAJO: 'COMPLETO',
    SERVICIOS_CATALOGO: 'COMPLETO', AGENDA_CITAS: 'COMPLETO', INVENTARIO: 'COMPLETO',
    FACTURACION: 'COMPLETO', REPORTES: 'COMPLETO', USUARIOS: 'SIN_ACCESO', CONFIGURACION: 'SIN_ACCESO',
  },
  SUPERVISOR: {
    DASHBOARD: 'COMPLETO', VEHICULOS_CLIENTES: 'COMPLETO', ORDENES_TRABAJO: 'COMPLETO',
    SERVICIOS_CATALOGO: 'LECTURA', AGENDA_CITAS: 'COMPLETO', INVENTARIO: 'LECTURA',
    FACTURACION: 'SIN_ACCESO', REPORTES: 'LECTURA', USUARIOS: 'SIN_ACCESO', CONFIGURACION: 'SIN_ACCESO',
  },
  MECANICO: {
    DASHBOARD: 'COMPLETO', VEHICULOS_CLIENTES: 'LECTURA', ORDENES_TRABAJO: 'COMPLETO',
    SERVICIOS_CATALOGO: 'LECTURA', AGENDA_CITAS: 'LECTURA', INVENTARIO: 'SIN_ACCESO',
    FACTURACION: 'SIN_ACCESO', REPORTES: 'SIN_ACCESO', USUARIOS: 'SIN_ACCESO', CONFIGURACION: 'SIN_ACCESO',
  },
  RECEPCIONISTA: {
    DASHBOARD: 'COMPLETO', VEHICULOS_CLIENTES: 'COMPLETO', ORDENES_TRABAJO: 'COMPLETO',
    SERVICIOS_CATALOGO: 'LECTURA', AGENDA_CITAS: 'COMPLETO', INVENTARIO: 'SIN_ACCESO',
    FACTURACION: 'COMPLETO', REPORTES: 'SIN_ACCESO', USUARIOS: 'SIN_ACCESO', CONFIGURACION: 'SIN_ACCESO',
  },
  ALMACEN: {
    DASHBOARD: 'COMPLETO', VEHICULOS_CLIENTES: 'SIN_ACCESO', ORDENES_TRABAJO: 'LECTURA',
    SERVICIOS_CATALOGO: 'SIN_ACCESO', AGENDA_CITAS: 'SIN_ACCESO', INVENTARIO: 'COMPLETO',
    FACTURACION: 'SIN_ACCESO', REPORTES: 'LECTURA', USUARIOS: 'SIN_ACCESO', CONFIGURACION: 'SIN_ACCESO',
  },
  CONTABILIDAD: {
    DASHBOARD: 'COMPLETO', VEHICULOS_CLIENTES: 'SIN_ACCESO', ORDENES_TRABAJO: 'SIN_ACCESO',
    SERVICIOS_CATALOGO: 'SIN_ACCESO', AGENDA_CITAS: 'SIN_ACCESO', INVENTARIO: 'SIN_ACCESO',
    FACTURACION: 'COMPLETO', REPORTES: 'COMPLETO', USUARIOS: 'SIN_ACCESO', CONFIGURACION: 'SIN_ACCESO',
  },
};
